
###
GET http://localhost:3000/comment

###
GET http://localhost:3000/comment/6747336ff957d508383435cc

###
GET http://localhost:3000/comment?postId=6747266ffb5681120bb550f5

###
POST  http://localhost:3000/comment
Content-Type: application/json

{
    "postId": "674f0eb7c8ec098c8fd76400",
    "content":"This is my first comment",
    "owner":"yuli"
}

###
PUT  http://localhost:3000/comment/6747336ff957d508383435cc
Content-Type: application/json

{
    "title": "My update comment",
    "content": "This is my update comment"
}

###
DELETE  http://localhost:3000/comment/674736544902d158c2a80164
Content-Type: application/json



