
###
GET http://localhost:3003/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzVmZmVmZGJmOTQ2ZmE1YTQ2NmVhNTgiLCJpYXQiOjE3MzQzNDQ2NTYsImV4cCI6MTczNDQzMTA1Nn0._CNMp0ZDgwGStLUrga7rA6i2en9ZRl6589O0FiopMfQ
###
GET http://localhost:3003/posts/674f0eb7c8ec098c8fd76400

###
GET http://localhost:3003/posts?owner=gil1234


###
POST  http://localhost:3003/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzhhMzM1N2NjZDk5N2JmMjc5MzYzNzYiLCJyYW5kIjowLjQ2NzU0MDgxOTI2ODY0ODU0LCJpYXQiOjE3MzcxMTAzNjgsImV4cCI6MTczNzExMjE2OH0.FdJfHvtcChPMAidRw3I-ocEYYg1DHanAnx3NdNZ4jno

{
    "title": "my third post",
    "content":"This is my third post",
    "owner":"gilMoshe"
}

###
PUT  http://localhost:3003/posts/674f0eb7c8ec098c8fd76400
Content-Type: application/json

{
    "title": "My update post",
    "content": "This is my update post",
    "owner": "gil1234"
}